### PR TITLE
Add instructions for usage

### PR DESCRIPTION
**Pull request by endolith**
I couldn't figure out how to actually use it.

### CODE REVIEW

**Comment by JustOff** [comment]
Thanks for your effort, but I do not think the “usage” section is essential.

PS: A new window opens only in Waterfox running in multi-process mode (see #2).

**Comment by felix-kolbe** [comment]
Uhm, I also had no clue how to use this. I checked about:addons in and out, searched there for addons to see any difference in the results, but nothing. Only much later I stumbled upon the menu item, and would never have guessed for this addon to add a special set of caa:... pages, as the ReadMe did not include no hint for that at all.

Thanks for all your efforts, anyway, but as it's already prepared you should pull the usage text.

**Comment by endolith** [comment]
Hi, can you please merge this?  There are no instructions for how to actually *use* this extension.  You install it and nothing obvious happens.  

This is the second time I've installed it and had no idea how to use it, and searched for instructions, and found how to use it, and started to submit a Pull Request to help others, before realizing I had already submitted a Pull Request over a year ago!

**Comment by JustOff** [comment]
I'm sorry but there is no.

**Comment by felix-kolbe** [comment]
Hi JustOff, no what? What do you mean? There is a commit above, isn't there?

**Comment by felix-kolbe** [comment]
Do you mind telling why? It would definitely help everyone doing anything for this project..

**Comment by JustOff** [comment]
https://github.com/JustOff/ca-archive/issues/45#issuecomment-489039344

**Pull request closed without merging**
